services:
  - type: web
    name: zorek
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: OMDB_KEY
        sync: false
      - key: TMDB_KEY
        sync: false
      - key: SPOONACULAR_KEY
        sync: false
      - key: SHEET_BEST_URL
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        value: https://zorek.onrender.com/oauth/spotify/callback
      - key: SEATGEEK_CLIENT_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
